/******************
FILENAME:  			clientSideValidation.js JAVASCRIPT FILE
AUTHOR:				ERIC PHUNG
PURPOSE: 			CUSTOM JAVASCRIPT FILE FOR OFFICIAL CLIENT-SIDE VALIDATION HTML
CREATED:			2014.01.2014 (eS)
MODIFIED: 			2014.01.2014 (eS);
					TESTED IN OPERA, CHROME, FIREFOX, SAFARI
					W3 VALIDATED
*******************/
$(document).ready(function() {
	alert("aSome")//DEBUG ALERT

});
